# Generated by Django 5.2.5 on 2025-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img_ru',
            field=models.ImageField(null=True, upload_to='laptops/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img_uz',
            field=models.ImageField(null=True, upload_to='laptops/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
