# Generated by Django 4.2 on 2025-08-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctabilizatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бранд', 'verbose_name_plural': 'Бранд'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': 'w сколько', 'verbose_name_plural': 'w сколько'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Товар описание', 'verbose_name_plural': 'Товар описание'},
        ),
        migrations.AlterModelOptions(
            name='solarpanel',
            options={'verbose_name': 'Стабилизаторы', 'verbose_name_plural': 'Стабилизаторы'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='rating',
            field=models.FloatField(default=0, verbose_name='райтинг'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='url товар'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ctabilizatory.category', verbose_name='таг'),
        ),
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='power',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='товар url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctabilizatory.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installment_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='рассрочка_цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='астивна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='старая_цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='популярность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='w сколько'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='обзоры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='товар url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ярлык'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name='просмотров'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='товар url'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='image',
            field=models.ImageField(upload_to='panels/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='power',
            field=models.IntegerField(verbose_name='w сколько'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
    ]
