# Generated by Django 5.2.5 on 2025-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctabilizatory', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='power',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='power',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='power',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
        migrations.AddField(
            model_name='power',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True, verbose_name='товар url'),
        ),
    ]
