# Generated by Django 4.2 on 2025-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
