# Generated by Django 5.2.5 on 2025-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_uz',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
