# Generated by Django 5.2.5 on 2025-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_title', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='икон'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
    ]
