# Generated by Django 5.2.5 on 2025-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_title', '0002_alter_card_desc_alter_card_icon_alter_card_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='card',
            name='desc_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='card',
            name='icon_ru',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='икон'),
        ),
        migrations.AddField(
            model_name='card',
            name='icon_uz',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='икон'),
        ),
        migrations.AddField(
            model_name='card',
            name='img_ru',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='card',
            name='img_uz',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок'),
        ),
    ]
