# Generated by Django 5.2.5 on 2025-08-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url товар')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('rating', models.FloatField(default=0, verbose_name='райтинг')),
            ],
            options={
                'verbose_name': 'Бранд',
                'verbose_name_plural': 'Бранд',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='имя')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='товар url')),
                ('slug_ru', models.SlugField(null=True, unique=True, verbose_name='товар url')),
                ('slug_uz', models.SlugField(null=True, unique=True, verbose_name='товар url')),
            ],
            options={
                'verbose_name': 'w сколько',
                'verbose_name_plural': 'w сколько',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='имя')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='товар url')),
                ('slug_ru', models.SlugField(null=True, unique=True, verbose_name='товар url')),
                ('slug_uz', models.SlugField(null=True, unique=True, verbose_name='товар url')),
            ],
            options={
                'verbose_name': 'Товар описание',
                'verbose_name_plural': 'Товар описание',
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('power', models.IntegerField(verbose_name='w сколько')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена')),
                ('image', models.ImageField(upload_to='panels/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Категория_магазина',
                'verbose_name_plural': 'Категория_магазина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skidka_product.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='URL товара')),
                ('slug_ru', models.SlugField(null=True, unique=True, verbose_name='URL товара')),
                ('slug_uz', models.SlugField(null=True, unique=True, verbose_name='URL товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='brand')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('reviews', models.IntegerField(default=0, verbose_name='Отзывы')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('installment_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена в рассрочку')),
                ('is_available', models.BooleanField(default=True, verbose_name='Активен')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('popularity', models.IntegerField(default=0, verbose_name='Популярность')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (W)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skidka_product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
