# Generated by Django 5.2.5 on 2025-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skidka_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='cкидка % пиши'),
        ),
    ]
