# Generated by Django 5.2.5 on 2025-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('desc_ru', models.TextField(null=True, verbose_name='Описание')),
                ('desc_uz', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
    ]
