# Generated by Django 5.2.5 on 2025-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('ru', models.TextField(blank=True)),
                ('uz', models.TextField(blank=True)),
            ],
        ),
    ]
