# Generated by Django 5.2.5 on 2025-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, unique=True)),
                ('ru', models.TextField(blank=True)),
                ('uz', models.TextField(blank=True)),
            ],
        ),
    ]
