# Generated by Django 5.2.5 on 2025-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_skidka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='скидка товара на %'),
        ),
    ]
