# Generated by Django 5.2.5 on 2025-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='power',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='power',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='power',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='power',
            name='slug_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_uz',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='slug_uz',
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='power_ru',
            field=models.IntegerField(null=True, verbose_name='w сколько'),
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='power_uz',
            field=models.IntegerField(null=True, verbose_name='w сколько'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
    ]
