# Generated by Django 5.2.5 on 2025-08-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0002_remove_brand_name_ru_remove_brand_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarpanel',
            name='power_ru',
        ),
        migrations.RemoveField(
            model_name='solarpanel',
            name='power_uz',
        ),
    ]
