# Generated by Django 4.2 on 2025-08-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0004_category_name_ru_category_name_uz_power_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_category.category', verbose_name='Имя'),
        ),
    ]
