# Generated by Django 4.2 on 2025-08-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность (W)'),
        ),
    ]
