# Generated by Django 4.2 on 2025-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адресс')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('iframe', models.TextField(help_text='Вставьте HTML iframe-код карты', verbose_name='Локация iframe')),
            ],
            options={
                'verbose_name': 'Локация-места',
                'verbose_name_plural': 'Локация-места',
            },
        ),
    ]
