# Generated by Django 5.2.5 on 2025-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='икон')),
                ('img', models.ImageField(upload_to='images/', verbose_name='фото')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
        ),
    ]
