# Generated by Django 4.2 on 2025-08-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='url товар')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('rating', models.FloatField(default=0, verbose_name='райтинг')),
            ],
            options={
                'verbose_name': 'Бранд',
                'verbose_name_plural': 'Бранд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vetrovaya_elektrostancii.category', verbose_name='таг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='товар url')),
            ],
            options={
                'verbose_name': 'w сколько',
                'verbose_name_plural': 'w сколько',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='товар url')),
            ],
            options={
                'verbose_name': 'Товар описание',
                'verbose_name_plural': 'Товар описание',
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('power', models.IntegerField(verbose_name='w сколько')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена')),
                ('image', models.ImageField(upload_to='panels/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Стабилизаторы',
                'verbose_name_plural': 'Стабилизаторы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='товар url')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='старая_цена')),
                ('color', models.CharField(max_length=50, verbose_name='цвет')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='ярлык')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='рейтинг')),
                ('reviews', models.IntegerField(default=0, verbose_name='обзоры')),
                ('in_stock', models.BooleanField(default=True, verbose_name='в наличии')),
                ('installment_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='рассрочка_цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='астивна')),
                ('views', models.IntegerField(default=0, verbose_name='просмотров')),
                ('popularity', models.IntegerField(default=0, verbose_name='популярность')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='w сколько')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetrovaya_elektrostancii.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
